version: "3.9"
services:
  ansible:
    build: docker/
    container_name: "ansible"
    command: "sleep infinity"
    links:
      - "webserver-ubuntu:webserver-ubuntu"
      - "webserver-centos:webserver-centos"
    volumes:
      - ./config:/etc/ansible
      - ./keys/ansible_key:/root/.ssh/id_rsa
      - ./keys/ansible_key.pub:/root/.ssh/id_rsa.pub
  webserver-ubuntu:
    build:
      context: docker/
      dockerfile: ubuntu_host.Dockerfile
    container_name: webserver-ubuntu
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:80
    volumes:
      - ./keys/ansible_key.pub:/root/.ssh/authorized_keys
  webserver-centos:
    build:
      context: docker/
      dockerfile: centos_host.Dockerfile
    container_name: webserver-centos
    ports:
      - 9090:80
    volumes:
      - ./keys/ansible_key.pub:/root/.ssh/authorized_keys