version: "3.9"
services:
  ansible:
    build: docker/
    container_name: "ansible"
    command: "sleep infinity"
    links:
      - "playground-ubuntu:playground-ubuntu"
      - "playground-centos:playground-centos"
    volumes:
      - $PWD/config:/etc/ansible
      - $PWD/keys/ansible_key:/root/.ssh/id_rsa:ro
  playground-ubuntu:
    build:
      context: docker/
      dockerfile: ubuntu_host.Dockerfile
    container_name: playground-ubuntu
    ports:
      - 8080:80
    volumes:
      - $PWD/keys/ansible_key.pub:/root/.ssh/authorized_keys
  playground-centos:
    build:
      context: docker/
      dockerfile: centos_host.Dockerfile
    container_name: playground-centos
    ports:
      - 9090:80
    volumes:
      - $PWD/keys/ansible_key.pub:/root/.ssh/authorized_keys